[project]
name = "stariodemo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "piccolo[sqlite]>=1.33.0",
    "pydantic==2.12.5",

    "stario==3.3.0",

    "tzdata==2025.3", # was getting weird utc error so need to import
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel",
]
